name: Update

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: git config --global user.name "Estafabot"
      - run: git config --global user.email "actions@users.noreply.github.com"
      - run: ./run
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          READ_APP_KEY: ${{ secrets.READ_APP_KEY }}
          READ_APP_SECRET: ${{ secrets.READ_APP_SECRET }}
          READ_ACCESS_TOKEN: ${{ secrets.READ_ACCESS_TOKEN }}
          READ_ACCESS_SECRET: ${{ secrets.READ_ACCESS_SECRET }}
